version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - 5173:5173
    environment:
      - HOST=0.0.0.0
      - PORT=5173
   