version: "3"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - 5174:5174
      - 4174:4174
    environment:
      - HOST=0.0.0.0
      - PORT=5174
      - PREVIEW_PORT=4174
